//
//  DictionaryView.swift
//  AMT
//
//  Created by Mochammad Athar Humam Ghazanfar on 21/08/26.
//

import SwiftUI

struct DictionaryView: View {
    @State private var viewModel: DictionaryViewModel

    init(dictionaryStore: LegalDictionaryStore = LegalDictionaryStore()) {
        _viewModel = State(initialValue: DictionaryViewModel(dictionaryStore: dictionaryStore))
    }

    var body: some View {
        Group {
            if viewModel.isShowingDetail {
                DictionaryDetailView(viewModel: viewModel)
                    .transition(.opacity.combined(with: .move(edge: .trailing)))
            } else {
                homeSearchView
                    .transition(.opacity.combined(with: .move(edge: .leading)))
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color(nsColor: .windowBackgroundColor))
        .animation(.easeInOut(duration: 0.22), value: viewModel.isShowingDetail)
    }

    // MARK: - Lawtionary Home Search Screen (Matching Mockup)

    private var homeSearchView: some View {
        VStack(spacing: 24) {
            Spacer()

            // Centered Title
            Text("Lawtionary")
                .font(.system(size: 32, weight: .bold))
                .foregroundStyle(.primary)

            // Search Bar
            HStack(spacing: 8) {
                TextField("Telusuri glosarium hukum...", text: $viewModel.searchText)
                    .textFieldStyle(.plain)
                    .font(.system(size: 14))
                    .onSubmit {
                        viewModel.lookupCurrentText()
                    }

                if viewModel.isLoading {
                    ProgressView()
                        .controlSize(.small)
                        .accessibilityLabel("Mencari istilah hukum")
                } else {
                    Button(action: {
                        viewModel.lookupCurrentText()
                    }) {
                        Image(systemName: "magnifyingglass")
                            .font(.system(size: 14))
                            .foregroundStyle(.secondary)
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            .background(Color.primary.opacity(0.04))
            .clipShape(RoundedRectangle(cornerRadius: 12))
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .strokeBorder(Color.primary.opacity(0.06), lineWidth: 1)
            )
            .frame(maxWidth: 480)

            // "Istilah Populer" Card Section
            // TODO: [AI Team] This card consumes `viewModel.popularTerms` generated by your recommendation model.
            VStack(alignment: .leading, spacing: 14) {
                Text("Istilah Populer")
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(.primary)

                // Chips Row
                HStack(spacing: 12) {
                    ForEach(viewModel.popularTerms) { term in
                        PopularTermChip(term: term) {
                            viewModel.selectPopularTerm(term)
                        }
                    }
                }
            }
            .padding(.horizontal, 18)
            .padding(.vertical, 16)
            .frame(maxWidth: 480, alignment: .leading)
            .background(Color.primary.opacity(0.03))
            .clipShape(RoundedRectangle(cornerRadius: 14))
            .overlay(
                RoundedRectangle(cornerRadius: 14)
                    .strokeBorder(Color.primary.opacity(0.05), lineWidth: 1)
            )

            Spacer()
            Spacer()
        }
        .padding(.horizontal, 24)
    }
}

// MARK: - Popular Term Chip Component

private struct PopularTermChip: View {
    let term: PopularTerm
    let action: () -> Void

    @State private var isHovered = false

    var body: some View {
        Button(action: action) {
            Text(term.name)
                .font(.system(size: 12, weight: .medium))
                .foregroundStyle(isHovered ? Color.accentColor : .primary.opacity(0.85))
                .padding(.horizontal, 8)
                .padding(.vertical, 4)
                .background(
                    RoundedRectangle(cornerRadius: 6)
                        .fill(isHovered ? Color.accentColor.opacity(0.08) : Color.clear)
                )
        }
        .buttonStyle(.plain)
        .onHover { hovering in
            isHovered = hovering
        }
    }
}

#Preview {
    DictionaryView(
        dictionaryStore: LegalDictionaryStore(entries: LegalDictionaryEntry.previewEntries)
    )
}
