//
//  DictionaryView.swift
//  AMT
//
//  Created by Mochammad Athar Humam Ghazanfar on 21/08/26.
//

import SwiftUI

struct DictionaryView: View {
    @State private var viewModel: DictionaryViewModel
    @Environment(\.colorScheme) private var colorScheme

    init(dictionaryStore: LegalDictionaryStore = LegalDictionaryStore()) {
        _viewModel = State(initialValue: DictionaryViewModel(dictionaryStore: dictionaryStore))
    }

    var body: some View {
        Group {
            if viewModel.isNotFound {
                dictionaryNotFoundView
                    .transition(.opacity.combined(with: .scale(scale: 0.96)))
            } else if viewModel.isShowingDetail {
                DictionaryDetailView(viewModel: viewModel)
                    .transition(.opacity.combined(with: .move(edge: .trailing)))
            } else {
                homeSearchView
                    .transition(.opacity.combined(with: .move(edge: .leading)))
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color(nsColor: .windowBackgroundColor))
        .animation(.easeInOut(duration: 0.22), value: viewModel.isShowingDetail)
        .animation(.easeInOut(duration: 0.22), value: viewModel.isNotFound)
    }

    // MARK: - Lawtionary Home Search Screen (Matching Mockup)

    private var homeSearchView: some View {
        VStack(spacing: 24) {
            Spacer()

            // Centered Title
            Text("Lawtionary")
                .font(.system(size: 32, weight: .bold))
                .foregroundStyle(.primary)

            // Search Bar
            HStack(spacing: 8) {
                TextField("Telusuri glosarium hukum...", text: $viewModel.searchText)
                    .textFieldStyle(.plain)
                    .font(.system(size: 14))
                    .onSubmit {
                        viewModel.lookupCurrentText()
                    }

                if viewModel.isLoading {
                    ProgressView()
                        .controlSize(.small)
                        .accessibilityLabel("Mencari istilah hukum")
                } else {
                    Button(action: {
                        viewModel.lookupCurrentText()
                    }) {
                        Image(systemName: "magnifyingglass")
                            .font(.system(size: 14))
                            .foregroundStyle(.secondary)
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            .background(Color.primary.opacity(0.04))
            .clipShape(RoundedRectangle(cornerRadius: 12))
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .strokeBorder(Color.primary.opacity(0.06), lineWidth: 1)
            )
            .frame(maxWidth: 480)

            if viewModel.isLoading, let progress = viewModel.semanticProgress {
                VStack(alignment: .leading, spacing: 6) {
                    HStack {
                        Text("Menyiapkan pencarian semantik")
                        Spacer()
                        Text(progress, format: .percent.precision(.fractionLength(0)))
                            .monospacedDigit()
                    }
                    .font(.caption)
                    .foregroundStyle(.secondary)

                    ProgressView(value: progress)
                        .progressViewStyle(.linear)
                }
                .frame(maxWidth: 480)
                .transition(.opacity)
            }

            // "Istilah Populer" Card Section
            // TODO: [AI Team] This card consumes `viewModel.popularTerms` generated by your recommendation model.
            VStack(alignment: .leading, spacing: 14) {
                Text("Istilah Populer")
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(.primary)

                // Chips Row
                HStack(spacing: 12) {
                    ForEach(viewModel.popularTerms) { term in
                        PopularTermChip(term: term) {
                            viewModel.selectPopularTerm(term)
                        }
                    }
                }
            }
            .padding(.horizontal, 18)
            .padding(.vertical, 16)
            .frame(maxWidth: 480, alignment: .leading)
            .background(Color.primary.opacity(0.03))
            .clipShape(RoundedRectangle(cornerRadius: 14))
            .overlay(
                RoundedRectangle(cornerRadius: 14)
                    .strokeBorder(Color.primary.opacity(0.05), lineWidth: 1)
            )

            Spacer()
            Spacer()
        }
        .padding(.horizontal, 24)
    }

    // MARK: - Term Not Found View (Matching Design Spec)

    private var dictionaryNotFoundView: some View {
        VStack(spacing: 28) {
            // Card Container
            VStack(spacing: 14) {
                // Circular Search Glass Icon
                ZStack {
                    Circle()
                        .fill(Color(white: 0.42))
                        .frame(width: 32, height: 32)

                    Image(systemName: "magnifyingglass")
                        .font(.system(size: 13, weight: .bold))
                        .foregroundStyle(.white)
                }

                // Header Title
                Text("Istilah yang kamu cari tidak ada")
                    .font(.system(size: 20, weight: .bold))
                    .foregroundStyle(.primary)
                    .multilineTextAlignment(.center)
                    .padding(.top, 4)

                // Description Subtitle
                Text("Cek kembali terkait penulisan atau istilah yang kamu cari")
                    .font(.system(size: 14, weight: .regular))
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
            }
            .padding(.horizontal, 36)
            .padding(.vertical, 36)
            .frame(maxWidth: 540)
            .background(
                RoundedRectangle(cornerRadius: 24)
                    .fill(colorScheme == .dark ? Color(white: 0.12) : Color(red: 0.97, green: 0.97, blue: 0.98))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 24)
                    .strokeBorder(Color(red: 0.32, green: 0.45, blue: 0.96), lineWidth: 2)
            )

            // "Kembali ke pencarian" Button
            Button(action: {
                viewModel.clearSearch()
            }) {
                Text("Kembali ke pencarian")
                    .font(.system(size: 14, weight: .semibold))
                    .foregroundStyle(.white)
                    .padding(.horizontal, 24)
                    .padding(.vertical, 12)
                    .background(Color(red: 0.08, green: 0.38, blue: 0.85))
                    .clipShape(RoundedRectangle(cornerRadius: 12))
            }
            .buttonStyle(.plain)
        }
        .padding(24)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

// MARK: - Popular Term Chip Component

private struct PopularTermChip: View {
    let term: PopularTerm
    let action: () -> Void

    @State private var isHovered = false

    var body: some View {
        Button(action: action) {
            Text(term.name)
                .font(.system(size: 12, weight: .medium))
                .foregroundStyle(isHovered ? Color.accentColor : .primary.opacity(0.85))
                .padding(.horizontal, 8)
                .padding(.vertical, 4)
                .background(
                    RoundedRectangle(cornerRadius: 6)
                        .fill(isHovered ? Color.accentColor.opacity(0.08) : Color.clear)
                )
        }
        .buttonStyle(.plain)
        .onHover { hovering in
            isHovered = hovering
        }
    }
}

#Preview {
    DictionaryView(
        dictionaryStore: LegalDictionaryStore(entries: LegalDictionaryEntry.previewEntries)
    )
}
