import Foundation

/// Identifies the configuration that produced a persisted document analysis.
///
/// A cached result is only restored when this profile still matches the active
/// pipeline. This prevents a result generated by an older prompt, validator,
/// model, or legal corpus from being presented as a current analysis.
struct AIConnectorAnalysisProfile: Codable, Equatable, Hashable, Sendable {
    static let currentVersion = "analysis-profile-v1"

    let version: String
    let pipelineVersion: String
    let reviewMode: AIConnectorReviewMode
    let modelVariant: AIConnectorModelVariant
    let thinkingEnabled: Bool
    let generationProfilePreset: AIConnectorGenerationProfilePreset
    let corpusVersion: String
    let semanticModelRevision: String
    let semanticEmbeddingSchema: String
    let semanticRetrievalProfile: String

    init(
        pipelineVersion: String,
        reviewMode: AIConnectorReviewMode,
        modelVariant: AIConnectorModelVariant,
        thinkingEnabled: Bool,
        generationProfilePreset: AIConnectorGenerationProfilePreset,
        corpusVersion: String,
        semanticModelRevision: String,
        semanticEmbeddingSchema: String,
        semanticRetrievalProfile: String,
        version: String = currentVersion
    ) {
        self.version = version
        self.pipelineVersion = pipelineVersion
        self.reviewMode = reviewMode
        self.modelVariant = modelVariant
        self.thinkingEnabled = thinkingEnabled
        self.generationProfilePreset = generationProfilePreset
        self.corpusVersion = corpusVersion
        self.semanticModelRevision = semanticModelRevision
        self.semanticEmbeddingSchema = semanticEmbeddingSchema
        self.semanticRetrievalProfile = semanticRetrievalProfile
    }
}
